// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: transport/internet/tunnel/config.proto

package tunnel

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address    string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Gateway    string   `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Mask       string   `protobuf:"bytes,4,opt,name=mask,proto3" json:"mask,omitempty"`
	Dns        []string `protobuf:"bytes,5,rep,name=dns,proto3" json:"dns,omitempty"`
	FixDnsLeak bool     `protobuf:"varint,6,opt,name=fix_dns_leak,json=fixDnsLeak,proto3" json:"fix_dns_leak,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_internet_tunnel_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_tunnel_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_transport_internet_tunnel_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Config) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Config) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *Config) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *Config) GetFixDnsLeak() bool {
	if x != nil {
		return x.FixDnsLeak
	}
	return false
}

var File_transport_internet_tunnel_config_proto protoreflect.FileDescriptor

var file_transport_internet_tunnel_config_proto_rawDesc = []byte{
	0x0a, 0x26, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x65, 0x74, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x78, 0x72, 0x61, 0x79, 0x2e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x65,
	0x74, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x98, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x61, 0x73, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x12,
	0x10, 0x0a, 0x03, 0x64, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6e,
	0x73, 0x12, 0x20, 0x0a, 0x0c, 0x66, 0x69, 0x78, 0x5f, 0x64, 0x6e, 0x73, 0x5f, 0x6c, 0x65, 0x61,
	0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x69, 0x78, 0x44, 0x6e, 0x73, 0x4c,
	0x65, 0x61, 0x6b, 0x42, 0x7c, 0x0a, 0x22, 0x63, 0x6f, 0x6d, 0x2e, 0x78, 0x72, 0x61, 0x79, 0x2e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x65, 0x74, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x01, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x74, 0x6c, 0x73, 0x2f, 0x78, 0x72, 0x61,
	0x79, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0xaa, 0x02, 0x1e, 0x58, 0x72, 0x61, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transport_internet_tunnel_config_proto_rawDescOnce sync.Once
	file_transport_internet_tunnel_config_proto_rawDescData = file_transport_internet_tunnel_config_proto_rawDesc
)

func file_transport_internet_tunnel_config_proto_rawDescGZIP() []byte {
	file_transport_internet_tunnel_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_tunnel_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_transport_internet_tunnel_config_proto_rawDescData)
	})
	return file_transport_internet_tunnel_config_proto_rawDescData
}

var file_transport_internet_tunnel_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transport_internet_tunnel_config_proto_goTypes = []interface{}{
	(*Config)(nil), // 0: xray.transport.internet.tunnel.Config
}
var file_transport_internet_tunnel_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_internet_tunnel_config_proto_init() }
func file_transport_internet_tunnel_config_proto_init() {
	if File_transport_internet_tunnel_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transport_internet_tunnel_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transport_internet_tunnel_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_tunnel_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_tunnel_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_tunnel_config_proto_msgTypes,
	}.Build()
	File_transport_internet_tunnel_config_proto = out.File
	file_transport_internet_tunnel_config_proto_rawDesc = nil
	file_transport_internet_tunnel_config_proto_goTypes = nil
	file_transport_internet_tunnel_config_proto_depIdxs = nil
}
